/**
 * Predict
 * Endpoints API for classification and other prediction services in SKIL
 *
 * OpenAPI spec version: 1.1.0-beta
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SkilClient) {
      root.SkilClient = {};
    }
    root.SkilClient.ClassificationResult = factory(root.SkilClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ClassificationResult model module.
   * @module ai/skymind/skil/model/ClassificationResult
   * @version 1.0.3-1
   */

  /**
   * Constructs a new <code>ClassificationResult</code>.
   * @alias module:ai/skymind/skil/model/ClassificationResult
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>ClassificationResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:ai/skymind/skil/model/ClassificationResult} obj Optional instance to populate.
   * @return {module:ai/skymind/skil/model/ClassificationResult} The populated <code>ClassificationResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('results')) {
        obj['results'] = ApiClient.convertToType(data['results'], ['Number']);
      }
      if (data.hasOwnProperty('probabilities')) {
        obj['probabilities'] = ApiClient.convertToType(data['probabilities'], ['Number']);
      }
      if (data.hasOwnProperty('minibatchId')) {
        obj['minibatchId'] = ApiClient.convertToType(data['minibatchId'], 'String');
      }
    }
    return obj;
  }

  /**
   * index classification results for the minibatch
   * @member {Array.<Number>} results
   */
  exports.prototype['results'] = undefined;
  /**
   * max probabilities for the batch items
   * @member {Array.<Number>} probabilities
   */
  exports.prototype['probabilities'] = undefined;
  /**
   * minibatch ID
   * @member {String} minibatchId
   */
  exports.prototype['minibatchId'] = undefined;



  return exports;
}));


