/**
 * Predict
 * Endpoints API for classification and other prediction services in SKIL
 *
 * OpenAPI spec version: 1.1.0-beta
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SkilClient) {
      root.SkilClient = {};
    }
    root.SkilClient.DeploymentObjects = factory(root.SkilClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DeploymentObjects model module.
   * @module ai/skymind/skil/model/DeploymentObjects
   * @version 1.1.0-beta
   */

  /**
   * Constructs a new <code>DeploymentObjects</code>.
   * @alias module:ai/skymind/skil/model/DeploymentObjects
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>DeploymentObjects</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:ai/skymind/skil/model/DeploymentObjects} obj Optional instance to populate.
   * @return {module:ai/skymind/skil/model/DeploymentObjects} The populated <code>DeploymentObjects</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('models')) {
        obj['models'] = ApiClient.convertToType(data['models'], [Object]);
      }
      if (data.hasOwnProperty('transforms')) {
        obj['transforms'] = ApiClient.convertToType(data['transforms'], [Object]);
      }
      if (data.hasOwnProperty('knn')) {
        obj['knn'] = ApiClient.convertToType(data['knn'], [Object]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<Object>} models
   */
  exports.prototype['models'] = undefined;
  /**
   * @member {Array.<Object>} transforms
   */
  exports.prototype['transforms'] = undefined;
  /**
   * @member {Array.<Object>} knn
   */
  exports.prototype['knn'] = undefined;



  return exports;
}));


