/**
 * Predict
 * Endpoints API for classification and other prediction services in SKIL
 *
 * OpenAPI spec version: 1.1.0-beta
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SkilClient) {
      root.SkilClient = {};
    }
    root.SkilClient.DeployModel = factory(root.SkilClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DeployModel model module.
   * @module ai/skymind/skil/model/DeployModel
   * @version 1.1.0-beta
   */

  /**
   * Constructs a new <code>DeployModel</code>.
   * @alias module:ai/skymind/skil/model/DeployModel
   * @class
   */
  var exports = function() {
    var _this = this;













  };

  /**
   * Constructs a <code>DeployModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:ai/skymind/skil/model/DeployModel} obj Optional instance to populate.
   * @return {module:ai/skymind/skil/model/DeployModel} The populated <code>DeployModel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('scale')) {
        obj['scale'] = ApiClient.convertToType(data['scale'], 'Number');
      }
      if (data.hasOwnProperty('uri')) {
        obj['uri'] = ApiClient.convertToType(data['uri'], 'String');
      }
      if (data.hasOwnProperty('modelType')) {
        obj['modelType'] = ApiClient.convertToType(data['modelType'], 'String');
      }
      if (data.hasOwnProperty('fileLocation')) {
        obj['fileLocation'] = ApiClient.convertToType(data['fileLocation'], 'String');
      }
      if (data.hasOwnProperty('jvmArgs')) {
        obj['jvmArgs'] = ApiClient.convertToType(data['jvmArgs'], 'String');
      }
      if (data.hasOwnProperty('subType')) {
        obj['subType'] = ApiClient.convertToType(data['subType'], 'String');
      }
      if (data.hasOwnProperty('labelsFileLocation')) {
        obj['labelsFileLocation'] = ApiClient.convertToType(data['labelsFileLocation'], 'String');
      }
      if (data.hasOwnProperty('extraArgs')) {
        obj['extraArgs'] = ApiClient.convertToType(data['extraArgs'], 'String');
      }
      if (data.hasOwnProperty('etlJson')) {
        obj['etlJson'] = ApiClient.convertToType(data['etlJson'], 'String');
      }
      if (data.hasOwnProperty('inputNames')) {
        obj['inputNames'] = ApiClient.convertToType(data['inputNames'], ['String']);
      }
      if (data.hasOwnProperty('outputNames')) {
        obj['outputNames'] = ApiClient.convertToType(data['outputNames'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Number} scale
   */
  exports.prototype['scale'] = undefined;
  /**
   * @member {String} uri
   */
  exports.prototype['uri'] = undefined;
  /**
   * @member {String} modelType
   */
  exports.prototype['modelType'] = undefined;
  /**
   * @member {String} fileLocation
   */
  exports.prototype['fileLocation'] = undefined;
  /**
   * @member {String} jvmArgs
   */
  exports.prototype['jvmArgs'] = undefined;
  /**
   * @member {String} subType
   */
  exports.prototype['subType'] = undefined;
  /**
   * @member {String} labelsFileLocation
   */
  exports.prototype['labelsFileLocation'] = undefined;
  /**
   * @member {String} extraArgs
   */
  exports.prototype['extraArgs'] = undefined;
  /**
   * @member {String} etlJson
   */
  exports.prototype['etlJson'] = undefined;
  /**
   * @member {Array.<String>} inputNames
   */
  exports.prototype['inputNames'] = undefined;
  /**
   * @member {Array.<String>} outputNames
   */
  exports.prototype['outputNames'] = undefined;



  return exports;
}));


