/**
 * Predict
 * Endpoints API for classification and other prediction services in SKIL
 *
 * OpenAPI spec version: 1.0.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SkilClient) {
      root.SkilClient = {};
    }
    root.SkilClient.MultiClassClassificationResult = factory(root.SkilClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The MultiClassClassificationResult model module.
   * @module ai/skymind/skil/model/MultiClassClassificationResult
   * @version 1.0.3-1
   */

  /**
   * Constructs a new <code>MultiClassClassificationResult</code>.
   * Represents all of the labels for a given classification
   * @alias module:ai/skymind/skil/model/MultiClassClassificationResult
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>MultiClassClassificationResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:ai/skymind/skil/model/MultiClassClassificationResult} obj Optional instance to populate.
   * @return {module:ai/skymind/skil/model/MultiClassClassificationResult} The populated <code>MultiClassClassificationResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('rankedOutcomes')) {
        obj['rankedOutcomes'] = ApiClient.convertToType(data['rankedOutcomes'], [['String']]);
      }
      if (data.hasOwnProperty('maxOutcomes')) {
        obj['maxOutcomes'] = ApiClient.convertToType(data['maxOutcomes'], ['String']);
      }
      if (data.hasOwnProperty('probabilities')) {
        obj['probabilities'] = ApiClient.convertToType(data['probabilities'], [['Number']]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<Array.<String>>} rankedOutcomes
   */
  exports.prototype['rankedOutcomes'] = undefined;
  /**
   * @member {Array.<String>} maxOutcomes
   */
  exports.prototype['maxOutcomes'] = undefined;
  /**
   * @member {Array.<Array.<Number>>} probabilities
   */
  exports.prototype['probabilities'] = undefined;



  return exports;
}));


