=begin
#Predict

#Endpoints API for classification and other prediction services in SKIL

OpenAPI spec version: 1.1.0-beta

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SkilCient::Token
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Token' do
  before do
    # run before each test
    @instance = SkilCient::Token.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Token' do
    it 'should create an instance of Token' do
      expect(@instance).to be_instance_of(SkilCient::Token)
    end
  end
  describe 'test attribute "token"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

