/* 
 * Predict
 *
 * Endpoints API for classification and other prediction services in SKIL
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Base64NDArrayBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Base64NDArrayBodyTests
    {
        // TODO uncomment below to declare an instance variable for Base64NDArrayBody
        //private Base64NDArrayBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Base64NDArrayBody
            //instance = new Base64NDArrayBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Base64NDArrayBody
        /// </summary>
        [Test]
        public void Base64NDArrayBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Base64NDArrayBody
            //Assert.IsInstanceOfType<Base64NDArrayBody> (instance, "variable 'instance' is a Base64NDArrayBody");
        }


        /// <summary>
        /// Test the property 'Ndarray'
        /// </summary>
        [Test]
        public void NdarrayTest()
        {
            // TODO unit test for the property 'Ndarray'
        }

    }

}
