# coding: utf-8

"""
    Predict
    Endpoints API for classification and other prediction services in SKIL  # noqa: E501
    OpenAPI spec version: 1.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import skil_client
from skil_client.models.log_request import LogRequest  # noqa: E501
from skil_client.rest import ApiException
from skil_client.rest import ApiException
from skil_client import ApiClient
from skil_client.configuration import Configuration
from skil_client.api.default_api import DefaultApi
from skil_client.models.token import Token

from pprint import pprint



class TestLogRequest(unittest.TestCase):

    def setUp(self):
        config = Configuration()
        config.host = "http://localhost:9008"
        config.api_key_prefix['authorization'] = 'Bearer'

        # initialize instance
        api_instance = skil_client.DefaultApi(api_client=ApiClient(configuration=config))
        return api_instance

    def tearDown(self):
        pass

    def testLogRequest(self):
        api_instance = self.setUp()
        creds = skil_client.Credentials(user_id="admin", password="admin")
        res = api_instance.login(creds)
        pprint(res)
        self.tearDown()


if __name__ == '__main__':
    unittest.main()