# coding: utf-8

"""
    Predict
    Endpoints API for classification and other prediction services in SKIL  # noqa: E501
    OpenAPI spec version: 1.1.0-beta
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import skil_client
from skil_client.models.file_upload import FileUpload  # noqa: E501
from skil_client.rest import ApiException
from skil_client import ApiClient
from skil_client.configuration import Configuration
from skil_client.api.default_api import DefaultApi

from pprint import pprint



class TestFileUpload(unittest.TestCase):

    def setUp(self):
        # set configuration
        config = Configuration()
        config.host = "http://localhost:9008"
        config.api_key_prefix['authorization'] = 'Bearer'

        # initialize instance
        api_instance = skil_client.DefaultApi(api_client=ApiClient(configuration=config))

        # get crednentials
        creds = skil_client.Credentials(user_id="admin", password="admin")
        res = api_instance.login(creds)
        config.api_key['authorization'] = res.to_dict()['token']

        return api_instance

    def tearDown(self):
        pass

    def testFileUpload(self):
        api_instance = self.setUp()
        deployment_name = "test"
        file = './model.pb'

        api_response = api_instance.upload(file = file)
        print(api_response)

        self.tearDown()


if __name__ == '__main__':
    unittest.main()

