/* 
 * Predict
 *
 * Endpoints API for classification and other prediction services in SKIL
 *
 * OpenAPI spec version: 1.1.0-beta
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Skymind.SKIL.Api;
using Skymind.SKIL.Model;
using Skymind.SKIL.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Skymind.SKIL.Test
{
    /// <summary>
    ///  Class for testing FileUploadList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FileUploadListTests
    {
        // TODO uncomment below to declare an instance variable for FileUploadList
        //private FileUploadList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FileUploadList
            //instance = new FileUploadList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FileUploadList
        /// </summary>
        [Test]
        public void FileUploadListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FileUploadList
            //Assert.IsInstanceOfType<FileUploadList> (instance, "variable 'instance' is a FileUploadList");
        }


        /// <summary>
        /// Test the property 'FileUploadResponseList'
        /// </summary>
        [Test]
        public void FileUploadResponseListTest()
        {
            // TODO unit test for the property 'FileUploadResponseList'
        }

    }

}
