/* 
 * Predict
 *
 * Endpoints API for classification and other prediction services in SKIL
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Skymind.SKIL.Api;
using Skymind.SKIL.Model;
using Skymind.SKIL.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Skymind.SKIL.Test
{
    /// <summary>
    ///  Class for testing LogBatch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LogBatchTests
    {
        // TODO uncomment below to declare an instance variable for LogBatch
        //private LogBatch instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LogBatch
            //instance = new LogBatch();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LogBatch
        /// </summary>
        [Test]
        public void LogBatchInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LogBatch
            //Assert.IsInstanceOfType<LogBatch> (instance, "variable 'instance' is a LogBatch");
        }


        /// <summary>
        /// Test the property 'Offset'
        /// </summary>
        [Test]
        public void OffsetTest()
        {
            // TODO unit test for the property 'Offset'
        }
        /// <summary>
        /// Test the property 'RowCount'
        /// </summary>
        [Test]
        public void RowCountTest()
        {
            // TODO unit test for the property 'RowCount'
        }
        /// <summary>
        /// Test the property 'Logs'
        /// </summary>
        [Test]
        public void LogsTest()
        {
            // TODO unit test for the property 'Logs'
        }

    }

}
