/* 
 * Predict
 *
 * Endpoints API for classification and other prediction services in SKIL
 *
 * OpenAPI spec version: 1.1.0-beta
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Skymind.SKIL.Api;
using Skymind.SKIL.Model;
using Skymind.SKIL.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Skymind.SKIL.Test
{
    /// <summary>
    ///  Class for testing NewDeployment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NewDeploymentTests
    {
        // TODO uncomment below to declare an instance variable for NewDeployment
        //private NewDeployment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NewDeployment
            //instance = new NewDeployment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NewDeployment
        /// </summary>
        [Test]
        public void NewDeploymentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NewDeployment
            //Assert.IsInstanceOfType<NewDeployment> (instance, "variable 'instance' is a NewDeployment");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
