/**
 * Predict
 * Endpoints API for classification and other prediction services in SKIL
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ai.skymind.skil.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

@ApiModel(description = "")
public class LogBatch implements Serializable {
  
  @SerializedName("offset")
  private Integer offset = null;
  @SerializedName("rowCount")
  private Integer rowCount = null;
  @SerializedName("logs")
  private String logs = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getOffset() {
    return offset;
  }
  public void setOffset(Integer offset) {
    this.offset = offset;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getRowCount() {
    return rowCount;
  }
  public void setRowCount(Integer rowCount) {
    this.rowCount = rowCount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLogs() {
    return logs;
  }
  public void setLogs(String logs) {
    this.logs = logs;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LogBatch logBatch = (LogBatch) o;
    return (this.offset == null ? logBatch.offset == null : this.offset.equals(logBatch.offset)) &&
        (this.rowCount == null ? logBatch.rowCount == null : this.rowCount.equals(logBatch.rowCount)) &&
        (this.logs == null ? logBatch.logs == null : this.logs.equals(logBatch.logs));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.offset == null ? 0: this.offset.hashCode());
    result = 31 * result + (this.rowCount == null ? 0: this.rowCount.hashCode());
    result = 31 * result + (this.logs == null ? 0: this.logs.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LogBatch {\n");
    
    sb.append("  offset: ").append(offset).append("\n");
    sb.append("  rowCount: ").append(rowCount).append("\n");
    sb.append("  logs: ").append(logs).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
