/**
 * Predict
 * Endpoints API for classification and other prediction services in SKIL
 *
 * OpenAPI spec version: 1.1.0-beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ai.skymind.skil.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

@ApiModel(description = "")
public class LogRequest implements Serializable {
  
  @SerializedName("offset")
  private Integer offset = null;
  @SerializedName("rowCount")
  private Integer rowCount = null;
  @SerializedName("head")
  private Boolean head = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getOffset() {
    return offset;
  }
  public void setOffset(Integer offset) {
    this.offset = offset;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getRowCount() {
    return rowCount;
  }
  public void setRowCount(Integer rowCount) {
    this.rowCount = rowCount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getHead() {
    return head;
  }
  public void setHead(Boolean head) {
    this.head = head;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LogRequest logRequest = (LogRequest) o;
    return (this.offset == null ? logRequest.offset == null : this.offset.equals(logRequest.offset)) &&
        (this.rowCount == null ? logRequest.rowCount == null : this.rowCount.equals(logRequest.rowCount)) &&
        (this.head == null ? logRequest.head == null : this.head.equals(logRequest.head));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.offset == null ? 0: this.offset.hashCode());
    result = 31 * result + (this.rowCount == null ? 0: this.rowCount.hashCode());
    result = 31 * result + (this.head == null ? 0: this.head.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LogRequest {\n");
    
    sb.append("  offset: ").append(offset).append("\n");
    sb.append("  rowCount: ").append(rowCount).append("\n");
    sb.append("  head: ").append(head).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
