// Models.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

protocol JSONEncodable {
    func encodeToJSON() -> Any
}

public enum ErrorResponse : Error {
    case HttpError(statusCode: Int, data: Data?, error: Error)
    case DecodeError(response: Data?, decodeError: DecodeError)
}

open class Response<T> {
    open let statusCode: Int
    open let header: [String: String]
    open let body: T?

    public init(statusCode: Int, header: [String: String], body: T?) {
        self.statusCode = statusCode
        self.header = header
        self.body = body
    }

    public convenience init(response: HTTPURLResponse, body: T?) {
        let rawHeader = response.allHeaderFields
        var header = [String:String]()
        for case let (key, value) as (String, String) in rawHeader {
            header[key] = value
        }
        self.init(statusCode: response.statusCode, header: header, body: body)
    }
}

public enum Decoded<ValueType> {
    case success(ValueType)
    case failure(DecodeError)
}

public extension Decoded {
    var value: ValueType? {
        switch self {
        case let .success(value):
            return value
        case .failure:
            return nil
        }
    }
}

public enum DecodeError {
    case typeMismatch(expected: String, actual: String)
    case missingKey(key: String)
    case parseError(message: String)
}

private var once = Int()
class Decoders {
    static fileprivate var decoders = Dictionary<String, ((AnyObject, AnyObject?) -> AnyObject)>()

    static func addDecoder<T>(clazz: T.Type, decoder: @escaping ((AnyObject, AnyObject?) -> Decoded<T>)) {
        let key = "\(T.self)"
        decoders[key] = { decoder($0, $1) as AnyObject }
    }

    static func decode<T>(clazz: T.Type, discriminator: String, source: AnyObject) -> Decoded<T> {
        let key = discriminator
        if let decoder = decoders[key], let value = decoder(source, nil) as? Decoded<T> {
            return value
        } else {
            return .failure(.typeMismatch(expected: String(describing: clazz), actual: String(describing: source)))
        }
    }

    static func decode<T>(clazz: [T].Type, source: AnyObject) -> Decoded<[T]> {
        if let sourceArray = source as? [AnyObject] {
            var values = [T]()
            for sourceValue in sourceArray {
                switch Decoders.decode(clazz: T.self, source: sourceValue, instance: nil) {
                case let .success(value):
                    values.append(value)
                case let .failure(error):
                    return .failure(error)
                }
            }
            return .success(values)
        } else {
            return .failure(.typeMismatch(expected: String(describing: clazz), actual: String(describing: source)))
        }
    }

    static func decode<T>(clazz: T.Type, source: AnyObject) -> Decoded<T> {
        switch Decoders.decode(clazz: T.self, source: source, instance: nil) {
    	    case let .success(value):
                return .success(value)
            case let .failure(error):
                return .failure(error)
        }
    }

    static open func decode<T: RawRepresentable>(clazz: T.Type, source: AnyObject) -> Decoded<T> {
        if let value = source as? T.RawValue {
            if let enumValue = T.init(rawValue: value) {
                return .success(enumValue)
            } else {
                return .failure(.typeMismatch(expected: "A value from the enumeration \(T.self)", actual: "\(value)"))
            }
        } else {
            return .failure(.typeMismatch(expected: "\(T.RawValue.self) matching a case from the enumeration \(T.self)", actual: String(describing: type(of: source))))
        }
    }

    static func decode<T, Key: Hashable>(clazz: [Key:T].Type, source: AnyObject) -> Decoded<[Key:T]> {
        if let sourceDictionary = source as? [Key: AnyObject] {
            var dictionary = [Key:T]()
            for (key, value) in sourceDictionary {
                switch Decoders.decode(clazz: T.self, source: value, instance: nil) {
                case let .success(value):
                    dictionary[key] = value
                case let .failure(error):
                    return .failure(error)
                }
            }
            return .success(dictionary)
        } else {
            return .failure(.typeMismatch(expected: String(describing: clazz), actual: String(describing: source)))
        }
    }

    static func decodeOptional<T: RawRepresentable>(clazz: T.Type, source: AnyObject?) -> Decoded<T?> {
        guard !(source is NSNull), source != nil else { return .success(nil) }
        if let value = source as? T.RawValue {
            if let enumValue = T.init(rawValue: value) {
                return .success(enumValue)
            } else {
                return .failure(.typeMismatch(expected: "A value from the enumeration \(T.self)", actual: "\(value)"))
            }
        } else {
            return .failure(.typeMismatch(expected: "\(T.RawValue.self) matching a case from the enumeration \(T.self)", actual: String(describing: type(of: source))))
        }
    }

    static func decode<T>(clazz: T.Type, source: AnyObject, instance: AnyObject?) -> Decoded<T> {
        initialize()
        if let sourceNumber = source as? NSNumber, let value = sourceNumber.int32Value as? T, T.self is Int32.Type {
            return .success(value)
        }
        if let sourceNumber = source as? NSNumber, let value = sourceNumber.int32Value as? T, T.self is Int64.Type {
     	    return .success(value)
        }
        if let intermediate = source as? String, let value = UUID(uuidString: intermediate) as? T, source is String, T.self is UUID.Type {
            return .success(value)
        }
        if let value = source as? T {
            return .success(value)
        }
        if let intermediate = source as? String, let value = Data(base64Encoded: intermediate) as? T {
            return .success(value)
        }

        let key = "\(T.self)"
        if let decoder = decoders[key], let value = decoder(source, instance) as? Decoded<T> {
           return value
        } else {
            return .failure(.typeMismatch(expected: String(describing: clazz), actual: String(describing: source)))
        }
    }

    //Convert a Decoded so that its value is optional. DO WE STILL NEED THIS?
    static func toOptional<T>(decoded: Decoded<T>) -> Decoded<T?> {
        return .success(decoded.value)
    }

    static func decodeOptional<T>(clazz: T.Type, source: AnyObject?) -> Decoded<T?> {
        if let source = source, !(source is NSNull) {
            switch Decoders.decode(clazz: clazz, source: source, instance: nil) {
            case let .success(value): return .success(value)
            case let .failure(error): return .failure(error)
            }
        } else {
            return .success(nil)
        }
    }
    
    static func decodeOptional<T>(clazz: [T].Type, source: AnyObject?) -> Decoded<[T]?> where T: RawRepresentable {
        if let source = source as? [AnyObject] {
            var values = [T]()
            for sourceValue in source {
                switch Decoders.decodeOptional(clazz: T.self, source: sourceValue) {
                case let .success(value): if let value = value { values.append(value) }
                case let .failure(error): return .failure(error)
                }
            }
            return .success(values)
        } else {
            return .success(nil)
        }
    }

    static func decodeOptional<T>(clazz: [T].Type, source: AnyObject?) -> Decoded<[T]?> {
        if let source = source as? [AnyObject] {
            var values = [T]()
            for sourceValue in source {
                switch Decoders.decode(clazz: T.self, source: sourceValue, instance: nil) {
                case let .success(value): values.append(value)
                case let .failure(error): return .failure(error)
                }
            }
            return .success(values)
        } else {
            return .success(nil)
        }
    }

    static func decodeOptional<T, Key: Hashable>(clazz: [Key:T].Type, source: AnyObject?) -> Decoded<[Key:T]?> {
        if let sourceDictionary = source as? [Key: AnyObject] {
            var dictionary = [Key:T]()
            for (key, value) in sourceDictionary {
                switch Decoders.decode(clazz: T.self, source: value, instance: nil) {
                case let .success(value): dictionary[key] = value
                case let .failure(error): return .failure(error)
                }
            }
            return .success(dictionary)
        } else {
            return .success(nil)
        }
    }

    static func decodeOptional<T: RawRepresentable, U: AnyObject>(clazz: T, source: AnyObject) -> Decoded<T?> where T.RawValue == U {
        if let value = source as? U {
            if let enumValue = T.init(rawValue: value) {
                return .success(enumValue)
            } else {
                return .failure(.typeMismatch(expected: "A value from the enumeration \(T.self)", actual: "\(value)"))
            }
        } else {
            return .failure(.typeMismatch(expected: "String", actual: String(describing: type(of: source))))
        }
    }


    private static var __once: () = {
        let formatters = [
            "yyyy-MM-dd",
            "yyyy-MM-dd'T'HH:mm:ssZZZZZ",
            "yyyy-MM-dd'T'HH:mm:ss.SSSZZZZZ",
            "yyyy-MM-dd'T'HH:mm:ss'Z'",
            "yyyy-MM-dd'T'HH:mm:ss.SSS",
            "yyyy-MM-dd HH:mm:ss"
        ].map { (format: String) -> DateFormatter in
            let formatter = DateFormatter()
            formatter.locale = Locale(identifier: "en_US_POSIX")
            formatter.dateFormat = format
            return formatter
        }
        // Decoder for Date
        Decoders.addDecoder(clazz: Date.self) { (source: AnyObject, instance: AnyObject?) -> Decoded<Date> in
           if let sourceString = source as? String {
                for formatter in formatters {
                    if let date = formatter.date(from: sourceString) {
                        return .success(date)
                    }
                }
            }
            if let sourceInt = source as? Int {
                // treat as a java date
                return .success(Date(timeIntervalSince1970: Double(sourceInt / 1000) ))
            }
            if source is String || source is Int {
                return .failure(.parseError(message: "Could not decode date"))
            } else {
                return .failure(.typeMismatch(expected: "String or Int", actual: "\(source)"))
            }
        }

        // Decoder for ISOFullDate
        Decoders.addDecoder(clazz: ISOFullDate.self) { (source: AnyObject, instance: AnyObject?) -> Decoded<ISOFullDate> in
            if let string = source as? String,
               let isoDate = ISOFullDate.from(string: string) {
                return .success(isoDate)
            } else {
            	return .failure(.typeMismatch(expected: "ISO date", actual: "\(source)"))
            }
        }

        // Decoder for [Base64NDArrayBody]
        Decoders.addDecoder(clazz: [Base64NDArrayBody].self) { (source: AnyObject, instance: AnyObject?) -> Decoded<[Base64NDArrayBody]> in
            return Decoders.decode(clazz: [Base64NDArrayBody].self, source: source)
        }

        // Decoder for Base64NDArrayBody
        Decoders.addDecoder(clazz: Base64NDArrayBody.self) { (source: AnyObject, instance: AnyObject?) -> Decoded<Base64NDArrayBody> in
            if let sourceDictionary = source as? [AnyHashable: Any] {
                let _result = instance == nil ? Base64NDArrayBody() : instance as! Base64NDArrayBody
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["ndarray"] as AnyObject?) {
                
                case let .success(value): _result.ndarray = value
                case let .failure(error): break
                
                }
                return .success(_result)
            } else {
                return .failure(.typeMismatch(expected: "Base64NDArrayBody", actual: "\(source)"))
            }
        }
        // Decoder for [ClassificationResult]
        Decoders.addDecoder(clazz: [ClassificationResult].self) { (source: AnyObject, instance: AnyObject?) -> Decoded<[ClassificationResult]> in
            return Decoders.decode(clazz: [ClassificationResult].self, source: source)
        }

        // Decoder for ClassificationResult
        Decoders.addDecoder(clazz: ClassificationResult.self) { (source: AnyObject, instance: AnyObject?) -> Decoded<ClassificationResult> in
            if let sourceDictionary = source as? [AnyHashable: Any] {
                let _result = instance == nil ? ClassificationResult() : instance as! ClassificationResult
                switch Decoders.decodeOptional(clazz: [Int32].self, source: sourceDictionary["results"] as AnyObject?) {
                
                case let .success(value): _result.results = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: [Double].self, source: sourceDictionary["probabilities"] as AnyObject?) {
                
                case let .success(value): _result.probabilities = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["minibatchId"] as AnyObject?) {
                
                case let .success(value): _result.minibatchId = value
                case let .failure(error): break
                
                }
                return .success(_result)
            } else {
                return .failure(.typeMismatch(expected: "ClassificationResult", actual: "\(source)"))
            }
        }
        // Decoder for [Credentials]
        Decoders.addDecoder(clazz: [Credentials].self) { (source: AnyObject, instance: AnyObject?) -> Decoded<[Credentials]> in
            return Decoders.decode(clazz: [Credentials].self, source: source)
        }

        // Decoder for Credentials
        Decoders.addDecoder(clazz: Credentials.self) { (source: AnyObject, instance: AnyObject?) -> Decoded<Credentials> in
            if let sourceDictionary = source as? [AnyHashable: Any] {
                let _result = instance == nil ? Credentials() : instance as! Credentials
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["userId"] as AnyObject?) {
                
                case let .success(value): _result.userId = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["password"] as AnyObject?) {
                
                case let .success(value): _result.password = value
                case let .failure(error): break
                
                }
                return .success(_result)
            } else {
                return .failure(.typeMismatch(expected: "Credentials", actual: "\(source)"))
            }
        }
        // Decoder for [DeployModel]
        Decoders.addDecoder(clazz: [DeployModel].self) { (source: AnyObject, instance: AnyObject?) -> Decoded<[DeployModel]> in
            return Decoders.decode(clazz: [DeployModel].self, source: source)
        }

        // Decoder for DeployModel
        Decoders.addDecoder(clazz: DeployModel.self) { (source: AnyObject, instance: AnyObject?) -> Decoded<DeployModel> in
            if let sourceDictionary = source as? [AnyHashable: Any] {
                let _result = instance == nil ? DeployModel() : instance as! DeployModel
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["name"] as AnyObject?) {
                
                case let .success(value): _result.name = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["scale"] as AnyObject?) {
                
                case let .success(value): _result.scale = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["uri"] as AnyObject?) {
                
                case let .success(value): _result.uri = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["modelType"] as AnyObject?) {
                
                case let .success(value): _result.modelType = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["fileLocation"] as AnyObject?) {
                
                case let .success(value): _result.fileLocation = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["jvmArgs"] as AnyObject?) {
                
                case let .success(value): _result.jvmArgs = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["subType"] as AnyObject?) {
                
                case let .success(value): _result.subType = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["labelsFileLocation"] as AnyObject?) {
                
                case let .success(value): _result.labelsFileLocation = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["extraArgs"] as AnyObject?) {
                
                case let .success(value): _result.extraArgs = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["etlJson"] as AnyObject?) {
                
                case let .success(value): _result.etlJson = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["inputNames"] as AnyObject?) {
                
                case let .success(value): _result.inputNames = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["outputNames"] as AnyObject?) {
                
                case let .success(value): _result.outputNames = value
                case let .failure(error): break
                
                }
                return .success(_result)
            } else {
                return .failure(.typeMismatch(expected: "DeployModel", actual: "\(source)"))
            }
        }
        // Decoder for [Deployment]
        Decoders.addDecoder(clazz: [Deployment].self) { (source: AnyObject, instance: AnyObject?) -> Decoded<[Deployment]> in
            return Decoders.decode(clazz: [Deployment].self, source: source)
        }

        // Decoder for Deployment
        Decoders.addDecoder(clazz: Deployment.self) { (source: AnyObject, instance: AnyObject?) -> Decoded<Deployment> in
            if let sourceDictionary = source as? [AnyHashable: Any] {
                let _result = instance == nil ? Deployment() : instance as! Deployment
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["id"] as AnyObject?) {
                
                case let .success(value): _result.id = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["name"] as AnyObject?) {
                
                case let .success(value): _result.name = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["deploymentSlug"] as AnyObject?) {
                
                case let .success(value): _result.deploymentSlug = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["status"] as AnyObject?) {
                
                case let .success(value): _result.status = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: DeploymentObjects.self, source: sourceDictionary["body"] as AnyObject?) {
                
                case let .success(value): _result.body = value
                case let .failure(error): break
                
                }
                return .success(_result)
            } else {
                return .failure(.typeMismatch(expected: "Deployment", actual: "\(source)"))
            }
        }
        // Decoder for [DeploymentObjects]
        Decoders.addDecoder(clazz: [DeploymentObjects].self) { (source: AnyObject, instance: AnyObject?) -> Decoded<[DeploymentObjects]> in
            return Decoders.decode(clazz: [DeploymentObjects].self, source: source)
        }

        // Decoder for DeploymentObjects
        Decoders.addDecoder(clazz: DeploymentObjects.self) { (source: AnyObject, instance: AnyObject?) -> Decoded<DeploymentObjects> in
            if let sourceDictionary = source as? [AnyHashable: Any] {
                let _result = instance == nil ? DeploymentObjects() : instance as! DeploymentObjects
                switch Decoders.decodeOptional(clazz: [Any].self, source: sourceDictionary["models"] as AnyObject?) {
                
                case let .success(value): _result.models = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: [Any].self, source: sourceDictionary["transforms"] as AnyObject?) {
                
                case let .success(value): _result.transforms = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: [Any].self, source: sourceDictionary["knn"] as AnyObject?) {
                
                case let .success(value): _result.knn = value
                case let .failure(error): break
                
                }
                return .success(_result)
            } else {
                return .failure(.typeMismatch(expected: "DeploymentObjects", actual: "\(source)"))
            }
        }
        // Decoder for [FileUpload]
        Decoders.addDecoder(clazz: [FileUpload].self) { (source: AnyObject, instance: AnyObject?) -> Decoded<[FileUpload]> in
            return Decoders.decode(clazz: [FileUpload].self, source: source)
        }

        // Decoder for FileUpload
        Decoders.addDecoder(clazz: FileUpload.self) { (source: AnyObject, instance: AnyObject?) -> Decoded<FileUpload> in
            if let sourceDictionary = source as? [AnyHashable: Any] {
                let _result = instance == nil ? FileUpload() : instance as! FileUpload
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["key"] as AnyObject?) {
                
                case let .success(value): _result.key = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["fileName"] as AnyObject?) {
                
                case let .success(value): _result.fileName = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["status"] as AnyObject?) {
                
                case let .success(value): _result.status = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["type"] as AnyObject?) {
                
                case let .success(value): _result.type = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["path"] as AnyObject?) {
                
                case let .success(value): _result.path = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["fileContent"] as AnyObject?) {
                
                case let .success(value): _result.fileContent = value
                case let .failure(error): break
                
                }
                return .success(_result)
            } else {
                return .failure(.typeMismatch(expected: "FileUpload", actual: "\(source)"))
            }
        }
        // Decoder for [FileUploadList]
        Decoders.addDecoder(clazz: [FileUploadList].self) { (source: AnyObject, instance: AnyObject?) -> Decoded<[FileUploadList]> in
            return Decoders.decode(clazz: [FileUploadList].self, source: source)
        }

        // Decoder for FileUploadList
        Decoders.addDecoder(clazz: FileUploadList.self) { (source: AnyObject, instance: AnyObject?) -> Decoded<FileUploadList> in
            if let sourceDictionary = source as? [AnyHashable: Any] {
                let _result = instance == nil ? FileUploadList() : instance as! FileUploadList
                switch Decoders.decodeOptional(clazz: [FileUpload].self, source: sourceDictionary["fileUploadResponseList"] as AnyObject?) {
                
                case let .success(value): _result.fileUploadResponseList = value
                case let .failure(error): break
                
                }
                return .success(_result)
            } else {
                return .failure(.typeMismatch(expected: "FileUploadList", actual: "\(source)"))
            }
        }
        // Decoder for [INDArray]
        Decoders.addDecoder(clazz: [INDArray].self) { (source: AnyObject, instance: AnyObject?) -> Decoded<[INDArray]> in
            return Decoders.decode(clazz: [INDArray].self, source: source)
        }

        // Decoder for INDArray
        Decoders.addDecoder(clazz: INDArray.self) { (source: AnyObject, instance: AnyObject?) -> Decoded<INDArray> in
            if let sourceDictionary = source as? [AnyHashable: Any] {
                let _result = instance == nil ? INDArray() : instance as! INDArray
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["array"] as AnyObject?) {
                
                case let .success(value): _result.array = value
                case let .failure(error): break
                
                }
                return .success(_result)
            } else {
                return .failure(.typeMismatch(expected: "INDArray", actual: "\(source)"))
            }
        }
        // Decoder for [JsonArrayResponse]
        Decoders.addDecoder(clazz: [JsonArrayResponse].self) { (source: AnyObject, instance: AnyObject?) -> Decoded<[JsonArrayResponse]> in
            return Decoders.decode(clazz: [JsonArrayResponse].self, source: source)
        }

        // Decoder for JsonArrayResponse
        Decoders.addDecoder(clazz: JsonArrayResponse.self) { (source: AnyObject, instance: AnyObject?) -> Decoded<JsonArrayResponse> in
            if let sourceDictionary = source as? [AnyHashable: Any] {
                let _result = instance == nil ? JsonArrayResponse() : instance as! JsonArrayResponse
                switch Decoders.decodeOptional(clazz: INDArray.self, source: sourceDictionary["array"] as AnyObject?) {
                
                case let .success(value): _result.array = value
                case let .failure(error): break
                
                }
                return .success(_result)
            } else {
                return .failure(.typeMismatch(expected: "JsonArrayResponse", actual: "\(source)"))
            }
        }
        // Decoder for [LogBatch]
        Decoders.addDecoder(clazz: [LogBatch].self) { (source: AnyObject, instance: AnyObject?) -> Decoded<[LogBatch]> in
            return Decoders.decode(clazz: [LogBatch].self, source: source)
        }

        // Decoder for LogBatch
        Decoders.addDecoder(clazz: LogBatch.self) { (source: AnyObject, instance: AnyObject?) -> Decoded<LogBatch> in
            if let sourceDictionary = source as? [AnyHashable: Any] {
                let _result = instance == nil ? LogBatch() : instance as! LogBatch
                switch Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["offset"] as AnyObject?) {
                
                case let .success(value): _result.offset = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["rowCount"] as AnyObject?) {
                
                case let .success(value): _result.rowCount = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["logs"] as AnyObject?) {
                
                case let .success(value): _result.logs = value
                case let .failure(error): break
                
                }
                return .success(_result)
            } else {
                return .failure(.typeMismatch(expected: "LogBatch", actual: "\(source)"))
            }
        }
        // Decoder for [LogRequest]
        Decoders.addDecoder(clazz: [LogRequest].self) { (source: AnyObject, instance: AnyObject?) -> Decoded<[LogRequest]> in
            return Decoders.decode(clazz: [LogRequest].self, source: source)
        }

        // Decoder for LogRequest
        Decoders.addDecoder(clazz: LogRequest.self) { (source: AnyObject, instance: AnyObject?) -> Decoded<LogRequest> in
            if let sourceDictionary = source as? [AnyHashable: Any] {
                let _result = instance == nil ? LogRequest() : instance as! LogRequest
                switch Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["offset"] as AnyObject?) {
                
                case let .success(value): _result.offset = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["rowCount"] as AnyObject?) {
                
                case let .success(value): _result.rowCount = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: Bool.self, source: sourceDictionary["head"] as AnyObject?) {
                
                case let .success(value): _result.head = value
                case let .failure(error): break
                
                }
                return .success(_result)
            } else {
                return .failure(.typeMismatch(expected: "LogRequest", actual: "\(source)"))
            }
        }
        // Decoder for [ModelStatus]
        Decoders.addDecoder(clazz: [ModelStatus].self) { (source: AnyObject, instance: AnyObject?) -> Decoded<[ModelStatus]> in
            return Decoders.decode(clazz: [ModelStatus].self, source: source)
        }

        // Decoder for ModelStatus
        Decoders.addDecoder(clazz: ModelStatus.self) { (source: AnyObject, instance: AnyObject?) -> Decoded<ModelStatus> in
            if let sourceDictionary = source as? [AnyHashable: Any] {
                let _result = instance == nil ? ModelStatus() : instance as! ModelStatus
                switch Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["status"] as AnyObject?) {
                
                case let .success(value): _result.status = value
                case let .failure(error): break
                
                }
                return .success(_result)
            } else {
                return .failure(.typeMismatch(expected: "ModelStatus", actual: "\(source)"))
            }
        }
        // Decoder for [MultiClassClassificationResult]
        Decoders.addDecoder(clazz: [MultiClassClassificationResult].self) { (source: AnyObject, instance: AnyObject?) -> Decoded<[MultiClassClassificationResult]> in
            return Decoders.decode(clazz: [MultiClassClassificationResult].self, source: source)
        }

        // Decoder for MultiClassClassificationResult
        Decoders.addDecoder(clazz: MultiClassClassificationResult.self) { (source: AnyObject, instance: AnyObject?) -> Decoded<MultiClassClassificationResult> in
            if let sourceDictionary = source as? [AnyHashable: Any] {
                let _result = instance == nil ? MultiClassClassificationResult() : instance as! MultiClassClassificationResult
                switch Decoders.decodeOptional(clazz: [[String]].self, source: sourceDictionary["rankedOutcomes"] as AnyObject?) {
                
                case let .success(value): _result.rankedOutcomes = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: [String].self, source: sourceDictionary["maxOutcomes"] as AnyObject?) {
                
                case let .success(value): _result.maxOutcomes = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: [[Double]].self, source: sourceDictionary["probabilities"] as AnyObject?) {
                
                case let .success(value): _result.probabilities = value
                case let .failure(error): break
                
                }
                return .success(_result)
            } else {
                return .failure(.typeMismatch(expected: "MultiClassClassificationResult", actual: "\(source)"))
            }
        }
        // Decoder for [NewDeployment]
        Decoders.addDecoder(clazz: [NewDeployment].self) { (source: AnyObject, instance: AnyObject?) -> Decoded<[NewDeployment]> in
            return Decoders.decode(clazz: [NewDeployment].self, source: source)
        }

        // Decoder for NewDeployment
        Decoders.addDecoder(clazz: NewDeployment.self) { (source: AnyObject, instance: AnyObject?) -> Decoded<NewDeployment> in
            if let sourceDictionary = source as? [AnyHashable: Any] {
                let _result = instance == nil ? NewDeployment() : instance as! NewDeployment
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["name"] as AnyObject?) {
                
                case let .success(value): _result.name = value
                case let .failure(error): break
                
                }
                return .success(_result)
            } else {
                return .failure(.typeMismatch(expected: "NewDeployment", actual: "\(source)"))
            }
        }
        // Decoder for [Prediction]
        Decoders.addDecoder(clazz: [Prediction].self) { (source: AnyObject, instance: AnyObject?) -> Decoded<[Prediction]> in
            return Decoders.decode(clazz: [Prediction].self, source: source)
        }

        // Decoder for Prediction
        Decoders.addDecoder(clazz: Prediction.self) { (source: AnyObject, instance: AnyObject?) -> Decoded<Prediction> in
            if let sourceDictionary = source as? [AnyHashable: Any] {
                let _result = instance == nil ? Prediction() : instance as! Prediction
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["id"] as AnyObject?) {
                
                case let .success(value): _result.id = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: Bool.self, source: sourceDictionary["needsPreProcessing"] as AnyObject?) {
                
                case let .success(value): _result.needsPreProcessing = value
                case let .failure(error): break
                
                }
                switch Decoders.decodeOptional(clazz: INDArray.self, source: sourceDictionary["prediction"] as AnyObject?) {
                
                case let .success(value): _result.prediction = value
                case let .failure(error): break
                
                }
                return .success(_result)
            } else {
                return .failure(.typeMismatch(expected: "Prediction", actual: "\(source)"))
            }
        }
        // Decoder for [Token]
        Decoders.addDecoder(clazz: [Token].self) { (source: AnyObject, instance: AnyObject?) -> Decoded<[Token]> in
            return Decoders.decode(clazz: [Token].self, source: source)
        }

        // Decoder for Token
        Decoders.addDecoder(clazz: Token.self) { (source: AnyObject, instance: AnyObject?) -> Decoded<Token> in
            if let sourceDictionary = source as? [AnyHashable: Any] {
                let _result = instance == nil ? Token() : instance as! Token
                switch Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["token"] as AnyObject?) {
                
                case let .success(value): _result.token = value
                case let .failure(error): break
                
                }
                return .success(_result)
            } else {
                return .failure(.typeMismatch(expected: "Token", actual: "\(source)"))
            }
        }
    }()

    static fileprivate func initialize() {
        _ = Decoders.__once
    }
}
