/* 
 * Predict
 *
 * Endpoints API for classification and other prediction services in SKIL
 *
 * OpenAPI spec version: 1.1.0-beta
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct JsonArrayResponse {
  #[serde(rename = "array")]
  array: Option<::models::IndArray>
}

impl JsonArrayResponse {
  pub fn new() -> JsonArrayResponse {
    JsonArrayResponse {
      array: None
    }
  }

  pub fn set_array(&mut self, array: ::models::IndArray) {
    self.array = Some(array);
  }

  pub fn with_array(mut self, array: ::models::IndArray) -> JsonArrayResponse {
    self.array = Some(array);
    self
  }

  pub fn array(&self) -> Option<&::models::IndArray> {
    self.array.as_ref()
  }

  pub fn reset_array(&mut self) {
    self.array = None;
  }

}



