mod base64_nd_array_body;
pub use self::base64_nd_array_body::Base64NdArrayBody;
mod classification_result;
pub use self::classification_result::ClassificationResult;
mod credentials;
pub use self::credentials::Credentials;
mod deploy_model;
pub use self::deploy_model::DeployModel;
mod deployment;
pub use self::deployment::Deployment;
mod deployment_objects;
pub use self::deployment_objects::DeploymentObjects;
mod file_upload;
pub use self::file_upload::FileUpload;
mod file_upload_list;
pub use self::file_upload_list::FileUploadList;
mod ind_array;
pub use self::ind_array::IndArray;
mod json_array_response;
pub use self::json_array_response::JsonArrayResponse;
mod log_batch;
pub use self::log_batch::LogBatch;
mod log_request;
pub use self::log_request::LogRequest;
mod model_status;
pub use self::model_status::ModelStatus;
mod multi_class_classification_result;
pub use self::multi_class_classification_result::MultiClassClassificationResult;
mod new_deployment;
pub use self::new_deployment::NewDeployment;
mod prediction;
pub use self::prediction::Prediction;
mod token;
pub use self::token::Token;

// TODO(farcaller): sort out files
pub struct File;
