/* 
 * Predict
 *
 * Endpoints API for classification and other prediction services in SKIL
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AI.Skymind.SKIL.Api;
using AI.Skymind.SKIL.Model;
using AI.Skymind.SKIL.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AI.Skymind.SKIL.Test
{
    /// <summary>
    ///  Class for testing Prediction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PredictionTests
    {
        // TODO uncomment below to declare an instance variable for Prediction
        //private Prediction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Prediction
            //instance = new Prediction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Prediction
        /// </summary>
        [Test]
        public void PredictionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Prediction
            //Assert.IsInstanceOfType<Prediction> (instance, "variable 'instance' is a Prediction");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'NeedsPreProcessing'
        /// </summary>
        [Test]
        public void NeedsPreProcessingTest()
        {
            // TODO unit test for the property 'NeedsPreProcessing'
        }
        /// <summary>
        /// Test the property '_Prediction'
        /// </summary>
        [Test]
        public void _PredictionTest()
        {
            // TODO unit test for the property '_Prediction'
        }

    }

}
