/*
 * Predict
 *
 * Endpoints API for classification and other prediction services in SKIL
 *
 * API version: 1.1.0-beta
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package skilclient

type Credentials struct {

	UserId string `json:"userId,omitempty"`

	Password string `json:"password,omitempty"`
}
