/*
 * Predict
 *
 * Endpoints API for classification and other prediction services in SKIL
 *
 * API version: 1.0.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package skilclient

type LogBatch struct {

	Offset int32 `json:"offset,omitempty"`

	RowCount int32 `json:"rowCount,omitempty"`

	Logs string `json:"logs,omitempty"`
}
