//
// ClassificationResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class ClassificationResult: JSONEncodable {

    /** index classification results for the minibatch */
    public var results: [Int32]?
    /** max probabilities for the batch items */
    public var probabilities: [Double]?
    /** minibatch ID */
    public var minibatchId: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["results"] = self.results?.encodeToJSON()
        nillableDictionary["probabilities"] = self.probabilities?.encodeToJSON()
        nillableDictionary["minibatchId"] = self.minibatchId

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

