//
// Deployment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Deployment: JSONEncodable {

    public var id: String?
    public var name: String?
    public var deploymentSlug: String?
    public var status: String?
    public var body: DeploymentObjects?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["deploymentSlug"] = self.deploymentSlug
        nillableDictionary["status"] = self.status
        nillableDictionary["body"] = self.body?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

